### ISSUE TITLE
Idea: Graph-based user recommendation

### ISSUE THREAD

**Issue by DonaldTsang** [SuzukiHonoka/Starx_Pixiv_Collector#11]
If I were to give you 300 artists of similar themes, is it possible to find other related artists that produces such themes (assume that we are going 3 levels deep, that means A liking B liking C liking D means all of them are related)?

**Comment by SuzukiHonoka** [comment]
Hello,
DonaldTsang.
Glad to hear your suggestions.
I understand your ideas,
but as so far,
My programming level is not so high,
So i can not to finish that function.
Thank you for your suggestions again.
